name: Deploy This Version

on:
  workflow_dispatch:
  push:
    paths-ignore:
    - '.github/**' # Ignore changes towards the .github directory
    branches-ignore:
    # Only trigger on version branches
    - gh-pages
    - master
    - devel

jobs:
  publish-this-version:
    runs-on: ubuntu-latest
    steps:
    # Get the name of the current branch
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - uses: actions/checkout@v2
      with:
        ref: ${{ steps.extract_branch.outputs.branch }}
        fetch-depth: 0
    #Copy the _config.yml file from master   
    - name: Copy Master Config File
      shell: bash
      run: git checkout origin/master -- _config.yml
    # Run a shell command to fix the config file
    - name: Fix Config File with current branch name
      shell: bash
      run: "sed -ri 's|(/latest)|/${{ steps.extract_branch.outputs.branch }}|g' _config.yml"
    # Deploy current version to gh-pages
    - name: Deploy current version to gh-pages
      uses: helaili/jekyll-action@master
      with:
        target_branch: gh-pages
        target_path: /${{ steps.extract_branch.outputs.branch }}
        keep_history: true
        token: ${{ secrets.GITHUB_TOKEN }}